### ISSUE TITLE
/login 502 error

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow-ansible#5]
On a new workstation when I deploy w/ Vagrant+Ansible the login throws a 502 error. I didn't see this on my laptop at home yesterday so it must be some environmental type of thing.

**Comment by edsu** [comment]
Here's a stack trace I see in the uwsgi log:

```
Traceback (most recent call last):
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/docnow/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/docnow/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/docnow/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./ui.py", line 47, in login
    return twitter.authorize(callback=callback_url)
  File "/opt/docnow/lib/python3.5/site-packages/flask_oauthlib/client.py", line 495, in authorize
    token = self.generate_request_token(callback)[0]
  File "/opt/docnow/lib/python3.5/site-packages/flask_oauthlib/client.py", line 580, in generate_request_token
    data=data,
flask_oauthlib.client.OAuthException: Failed to generate request token
```

**Comment by kayiwa** [comment]
Fixed by this commit. https://github.com/DocNow/dnflow-ansible/commit/e87dc4bf51abb41296371cdaed3064d6ce33e87d Thanks @edsu!
